"""First Migration

Revision ID: 21ca175f8a14
Revises: 
Create Date: 2023-04-18 21:03:30.433991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ca175f8a14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pallete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color1', sa.String(), nullable=True),
    sa.Column('color2', sa.String(), nullable=True),
    sa.Column('color3', sa.String(), nullable=True),
    sa.Column('color4', sa.String(), nullable=True),
    sa.Column('color5', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pallete_id'), 'pallete', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pallete_id'), table_name='pallete')
    op.drop_table('pallete')
    # ### end Alembic commands ###
